### ISSUE TITLE
Allow user to specify more specific constraints on the schedule

### ISSUE THREAD

**Issue by wyndro** [JustinHuPrime/YearlyPrologue#3]
Create constraints that the user can use to personalize their schedule.

Some examples

- [ ] No classes before or after a particular time
- [ ] Lunch break, create a x hour window within x time frame (ie 1 free hour between 11am and 1pm)
- [ ] No classes on a particular day
- [ ] No long class times (don't have 6 hours of consecutive class times)
- [ ] Prerequisite checking of some kind? ie if I want to take both 304 and 404, 304 must come in term 1 and 404 must come in term 2
- [ ] Credit weights per term, minimum/maximum

**Comment by JustinHuPrime** [comment]
This issue has been split into multiple issues.
